<template>
    <div class="echarts-dom" ref="echart"></div>
</template>

<script>
export default {
    mounted() {
        let data = [
            { name: 'noxussj', value: 89459 },
            { name: 'visualMap', value: 22199 },
            { name: 'continuous', value: 10288 },
            { name: 'contoller', value: 620 },
            { name: 'series', value: 274470 },
            { name: 'gauge', value: 12311 },
            { name: 'detail', value: 1206 },
            { name: 'piecewise', value: 4885 },
            { name: 'textStyle', value: 32294 },
            { name: 'markPoint', value: 18574 },
            { name: 'pie', value: 38929 },
            { name: 'roseType', value: 969 },
            { name: 'label', value: 37517 },
            { name: 'emphasis', value: 12053 },
            { name: 'yAxis', value: 57299 },
            { name: 'name', value: 15418 },
            { name: 'type', value: 22905 },
            { name: 'gridIndex', value: 5146 },
            { name: 'normal', value: 49487 },
            { name: 'itemStyle', value: 33837 },
            { name: 'min', value: 4500 },
            { name: 'silent', value: 5744 },
            { name: 'animation', value: 4840 },
            { name: 'offsetCenter', value: 232 },
            { name: 'inverse', value: 3706 },
            { name: 'borderColor', value: 4812 },
            { name: 'markLine', value: 16578 },
            { name: 'line', value: 76970 },
            { name: 'radiusAxis', value: 6704 },
            { name: 'radar', value: 15964 },
            { name: 'data', value: 60679 },
            { name: 'dataZoom', value: 24347 },
            { name: 'tooltip', value: 43420 },
            { name: 'toolbox', value: 25222 },
            { name: 'geo', value: 16904 },
            { name: 'parallelAxis', value: 4029 },
            { name: 'parallel', value: 5319 },
            { name: 'max', value: 3393 },
            { name: 'bar', value: 43066 },
            { name: 'heatmap', value: 3110 },
            { name: 'map', value: 20285 },
            { name: 'animationDuration', value: 3425 },
            { name: 'animationDelay', value: 2431 },
            { name: 'splitNumber', value: 5175 },
            { name: 'axisLine', value: 12738 },
            { name: 'lineStyle', value: 19601 },
            { name: 'splitLine', value: 7133 },
            { name: 'axisTick', value: 8831 },
            { name: 'axisLabel', value: 17516 },
            { name: 'pointer', value: 590 },
            { name: 'color', value: 23426 },
            { name: 'title', value: 38497 },
            { name: 'formatter', value: 15214 },
            { name: 'slider', value: 7236 },
            { name: 'legend', value: 66514 },
            { name: 'grid', value: 28516 },
            { name: 'smooth', value: 1295 },
            { name: 'smoothMonotone', value: 696 },
            { name: 'sampling', value: 757 },
            { name: 'feature', value: 12815 },
            { name: 'saveAsImage', value: 2616 },
            { name: 'polar', value: 6279 },
            { name: 'calculable', value: 879 },
            { name: 'backgroundColor', value: 9419 },
            { name: 'excludeComponents', value: 130 },
            { name: 'show', value: 20620 },
            { name: 'text', value: 2592 },
            { name: 'icon', value: 2782 },
            { name: 'dimension', value: 478 },
            { name: 'inRange', value: 1060 },
            { name: 'animationEasing', value: 2983 },
            { name: 'animationDurationUpdate', value: 2259 },
            { name: 'animationDelayUpdate', value: 2236 },
            { name: 'animationEasingUpdate', value: 2213 },
            { name: 'xAxis', value: 89459 },
            { name: 'angleAxis', value: 5469 },
            { name: 'showTitle', value: 484 },
            { name: 'dataView', value: 2754 },
            { name: 'restore', value: 932 },
            { name: 'timeline', value: 10104 },
            { name: 'range', value: 477 },
            { name: 'value', value: 5732 },
            { name: 'precision', value: 878 },
            { name: 'target', value: 1433 },
            { name: 'zlevel', value: 5361 },
            { name: 'symbol', value: 8718 },
            { name: 'interval', value: 7964 },
            { name: 'symbolSize', value: 5300 },
            { name: 'showSymbol', value: 1247 },
            { name: 'inside', value: 8913 },
            { name: 'xAxisIndex', value: 3843 },
            { name: 'orient', value: 4205 },
            { name: 'boundaryGap', value: 5073 },
            { name: 'nameGap', value: 4896 },
            { name: 'zoomLock', value: 571 },
            { name: 'hoverAnimation', value: 2307 },
            { name: 'legendHoverLink', value: 3553 },
            { name: 'stack', value: 2907 },
            { name: 'throttle', value: 466 },
            { name: 'connectNulls', value: 897 },
            { name: 'clipOverflow', value: 826 },
            { name: 'startValue', value: 551 },
            { name: 'minInterval', value: 3292 },
            { name: 'opacity', value: 3097 },
            { name: 'splitArea', value: 4775 },
            { name: 'filterMode', value: 635 },
            { name: 'end', value: 409 },
            { name: 'left', value: 6475 },
            { name: 'funnel', value: 2238 },
            { name: 'lines', value: 6403 },
            { name: 'baseline', value: 431 },
            { name: 'align', value: 2608 },
            { name: 'coord', value: 897 },
            { name: 'nameTextStyle', value: 7477 },
            { name: 'width', value: 4338 },
            { name: 'shadowBlur', value: 4493 },
            { name: 'effect', value: 929 },
            { name: 'period', value: 225 },
            { name: 'areaColor', value: 631 },
            { name: 'borderWidth', value: 3654 },
            { name: 'nameLocation', value: 4418 },
            { name: 'position', value: 11723 },
            { name: 'containLabel', value: 1701 },
            { name: 'scatter', value: 10718 },
            { name: 'areaStyle', value: 5310 },
            { name: 'scale', value: 3859 },
            { name: 'pieces', value: 414 },
            { name: 'categories', value: 1000 },
            { name: 'selectedMode', value: 3825 },
            { name: 'itemSymbol', value: 273 },
            { name: 'effectScatter', value: 7147 },
            { name: 'fontStyle', value: 3376 },
            { name: 'fontSize', value: 3386 },
            { name: 'margin', value: 1034 },
            { name: 'iconStyle', value: 2257 },
            { name: 'link', value: 1366 },
            { name: 'axisPointer', value: 5245 },
            { name: 'showDelay', value: 896 },
            { name: 'graph', value: 22194 },
            { name: 'subtext', value: 1442 },
            { name: 'selected', value: 2881 },
            { name: 'barCategoryGap', value: 827 },
            { name: 'barGap', value: 1094 },
            { name: 'barWidth', value: 1521 },
            { name: 'coordinateSystem', value: 3622 },
            { name: 'barBorderRadius', value: 284 },
            { name: 'z', value: 4014 },
            { name: 'polarIndex', value: 1456 },
            { name: 'shadowOffsetX', value: 3046 },
            { name: 'shadowColor', value: 3771 },
            { name: 'shadowOffsetY', value: 2475 },
            { name: 'height', value: 1988 },
            { name: 'barMinHeight', value: 575 },
            { name: 'lang', value: 131 },
            { name: 'symbolRotate', value: 2752 },
            { name: 'symbolOffset', value: 2549 },
            { name: 'showAllSymbol', value: 942 },
            { name: 'transitionDuration', value: 993 },
            { name: 'bottom', value: 3724 },
            { name: 'fillerColor', value: 229 },
            { name: 'nameMap', value: 1249 },
            { name: 'barMaxWidth', value: 747 },
            { name: 'radius', value: 2103 },
            { name: 'center', value: 2425 },
            { name: 'magicType', value: 3276 },
            { name: 'labelPrecision', value: 248 },
            { name: 'option', value: 654 },
            { name: 'seriesIndex', value: 935 },
            { name: 'controlPosition', value: 121 },
            { name: 'itemGap', value: 3188 },
            { name: 'padding', value: 3481 },
            { name: 'shadowStyle', value: 347 },
            { name: 'boxplot', value: 1394 },
        ];

        this.$echarts.dispatch('wordCloudSimple', {
            dom: this.$refs.echart,
            param: {
                data: data,
            },
            opt: {},
        });
    },
};
</script>
